require_relative 'config/environment'

desc "Loads a console"
task :console do
    Pry.start
end

desc "Say hello"
task :hi do
    puts "Hi everybody!"
end

desc "Set up database"
task :set_up_db do

    author_sql = <<-SQL
        CREATE TABLE IF NOT EXISTS authors(
            id integer PRIMARY KEY,
            name TEXT)
    SQL

    DB.execute(author_sql)

end

